# Generated by Django 3.2.11 on 2022-01-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aakashvani', '0003_aakashvani'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
    ]
