"""empty message

Revision ID: 2593b212a862
Revises: 68fc0b65e647
Create Date: 2022-01-08 23:06:09.139403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2593b212a862'
down_revision = '68fc0b65e647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'priority')
    # ### end Alembic commands ###
