"""empty message

Revision ID: 766e1595ccaa
Revises: 2593b212a862
Create Date: 2022-01-10 12:34:13.637103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766e1595ccaa'
down_revision = '2593b212a862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aakashvani', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'priority')
    op.drop_column('aakashvani', 'priority')
    # ### end Alembic commands ###
