# Generated by Django 3.2.11 on 2022-01-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('btn', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
